DreamTeach/src/Entity/Qcm.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QcmRepository")
 */
class Qcm
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $uuid;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Student", inversedBy="qcms")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author_id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deadline;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $visible;

    /**
     * @ORM\Column(name="title", type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\OneToMany(targetEntity="Question", mappedBy="qcm", cascade={"all"})
     */
    private $questions;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->uuid = Uuid::uuid4()->toString();
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthorId(): ?Student
    {
        return $this->author_id;
    }

    public function setAuthorId(?Student $author_id): self
    {
        $this->author_id = $author_id;

        return $this;
    }

    public function getDeadline(): ?\DateTimeInterface
    {
        return $this->deadline;
    }

    public function setDeadline(?\DateTimeInterface $deadline): self
    {
        $this->deadline = $deadline;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getQuestions()
    {
        return $this->questions;
    }

    /**
     * @param mixed $questions
     */
    public function setQuestions($questions): void
    {
        $this->questions = $questions;
    }

    public function addQuestion(Question $question)
    {
        $this->questions[] = $question;
        $question->setQcm($this);

        return $this;
    }

    public function removeQuestion(Question $question)
    {
        //TODO
    }

    /**
     * @return string
     */
    public function getUuid(): string
    {
        return $this->uuid;
    }

    /**
     * @param string $uuid
     */
    public function setUuid(string $uuid): void
    {
        $this->uuid = $uuid;
    }

}

DreamTeach/templates/base.mail.html.twig
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Template mailing Alsacreations</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style type="text/css">
        /* Fonts and Content */
        body, td { font-family: 'Helvetica Neue', Arial, Helvetica, Geneva, sans-serif; font-size:14px; }
        body { background-color: #2A374E; margin: 0; padding: 0; -webkit-text-size-adjust:none; -ms-text-size-adjust:none; }
        h2{ padding-top:12px; /* ne fonctionnera pas sous Outlook 2007+ */color:#0E7693; font-size:22px; }

    </style>

</head>
<body style="margin:0px; padding:0px; -webkit-text-size-adjust:none;">

<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:rgb(42, 55, 78)" >
    <tbody>
    <tr>
        <td align="center" bgcolor="#2A374E">
            <table  cellpadding="0" cellspacing="0" border="0">
                <tbody>
                <tr>
                    <td class="w640"  width="640" height="10"></td>
                </tr>

                <tr>
                    <td class="w640"  width="640" height="10"></td>
                </tr>

                <!-- entete -->
                <tr class="pagetoplogo">
                    <td class="w640"  width="640">
                        <table  class="w640"  width="640" cellpadding="0" cellspacing="0" border="0" bgcolor="#F2F0F0">
                            <tbody>
                            <tr>
                                <td class="w30"  width="30"></td>
                                <td  class="w580"  width="580" valign="middle" align="left">
                                    <div class="pagetoplogo-content">
                                        <img class="w580" style="text-decoration: none; display: block; color:#476688; font-size:30px;" src="https://brde.fr/ptutdt/tom_bg.jpg" alt="Mon Logo" width="482" height="108"/>
                                    </div>
                                </td>
                                <td class="w30"  width="30"></td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>

                <!-- separateur horizontal -->
                <tr>
                    <td  class="w640"  width="640" height="1" bgcolor="#d7d6d6"></td>
                </tr>

                <!-- contenu -->
                <tr class="content">
                    <td class="w640" class="w640"  width="640" bgcolor="#ffffff">
                        <table class="w640"  width="640" cellpadding="0" cellspacing="0" border="0">
                            <tbody>
                            <tr>
                                <td  class="w30"  width="30"></td>
                                <td  class="w580"  width="580">
                                    <!-- une zone de contenu -->
                                    <table class="w580"  width="580" cellpadding="0" cellspacing="0" border="0">
                                        <tbody>
                                        <tr>
                                            <td class="w580"  width="580">
                                                <h2 style="color:#0E7693; font-size:22px; padding-top:12px;">
                                                    Un titre ici  </h2>

                                                <div align="left" class="article-content">
                                                    <p> On peut mettre des paragraphes</p>
                                                    <p>
                                                        Chocolate bar marshmallow dessert wafer topping sugar plum pudding. Dragée dessert gummi bears brownie powder soufflé tootsie roll <a href="">cotton candy tiramisu. </a>
                                                    </p>
                                                    <p>
                                                        Lemon drops icing croissant. Sweet cotton candy macaroon gingerbread chocolate bar wafer cotton candy powder sugar plum.
                                                    </p>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="w580"  width="580" height="1" bgcolor="#c7c5c5"></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <!-- fin zone -->

                                    <!-- une autre zone de contenu -->
                                    <table class="w580"  width="580" cellspacing="0" cellpadding="0" border="0">
                                        <tbody>
                                        <tr>
                                            <td colspan="3">
                                                <h2 style="color:#0E7693; font-size:22px; padding-top:12px;">
                                                    Une zone avec deux colonnes </h2>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="w275"  width="275" valign="top">
                                                <div align="left" class="article-content">
                                                    <p> Avec des listes ça marche aussi </p>
                                                    <ul>
                                                        <li> des kiwis</li>
                                                        <li> des chatons</li>
                                                        <li> des citrons </li>
                                                    </ul>
                                                </div>
                                            </td>
                                            <td class="w30"  width="30" class="w30"></td>
                                            <td class="w275"  width="275" valign="top">
                                                <div align="left" class="article-content">
                                                    <p> Lemon drops icing croissant. Sweet cotton candy macaroon gingerbread chocolate bar wafer cotton candy powder sugar plum. </p>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="3" class="w580" height="1" bgcolor="#c7c5c5"></td>
                                        </tr>

                                        </tbody>
                                    </table>

                                    <table class="w580"  width="580" cellpadding="0" cellspacing="0" border="0">
                                        <tbody>
                                        <tr>
                                            <td colspan="5">
                                                <h2 style="color:#0E7693; font-size:22px; padding-top:12px;">
                                                    Mise en page 3 colonnes </h2>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="w180"  width="180" valign="top">
                                                <div align="left" class="article-content">
                                                    <p>Des kiwis et des chatons !! Des kiwis et des chatons !!</p>
                                                </div>
                                            </td>

                                            <td class="w20"  width="20"></td>
                                            <td class="w180"  width="180" valign="top">
                                                <div align="left" class="article-content">
                                                    <p>Des kiwis et des chatons !! Des kiwis et des chatons !!</p>
                                                </div>
                                            </td>

                                            <td class="w20"  width="20"></td>
                                            <td class="w180"  width="180" valign="top">
                                                <div align="left" class="article-content">
                                                    <p><img class="w180" width="180" src="https://brde.fr/ptutdt/tom_bg.jpg" alt="un chaton"/></p>
                                                </div>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td colspan="5" class="w580"  width="580" height="1" bgcolor="#c7c5c5"></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </td>
                                <td class="w30" class="w30"  width="30"></td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>

                <!--  separateur horizontal de 15px de  haut-->
                <tr>
                    <td class="w640"  width="640" height="15" bgcolor="#ffffff"></td>
                </tr>

                <!-- pied de page -->
                <tr class="pagebottom">
                    <td class="w640"  width="640">
                        <table class="w640"  width="640" cellpadding="0" cellspacing="0" border="0" bgcolor="#c7c7c7">
                            <tbody>
                            <tr>
                                <td colspan="5" height="10"></td>
                            </tr>
                            <tr>
                                <td class="w30"  width="30"></td>
                                <td class="w580"  width="580" valign="top">
                                    <p align="right" class="pagebottom-content-left">
                                        <a style="color:#255D5C;" href="#"><span style="color:#255D5C;">DreamTeach le 💯</span></a>
                                    </p>
                                </td>

                                <td class="w30"  width="30"></td>
                            </tr>
                            <tr>
                                <td colspan="5" height="10"></td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td class="w640"  width="640" height="60"></td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>

DreamTeach/templates/conversation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}

{% block stylesheets %}
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.js"></script>
{% endblock %}
{% block javascripts %}
    <script>

        var element = document.getElementById("messageScroll");
        element.scrollTop = element.scrollHeight;

    </script>
{% endblock %}

{% block body %}
    <style>
        /* CSS talk bubble */
        .talk-bubble {
            margin: 40px;
            display: inline-block;
            position: relative;
            width: 500px;
            height: auto;
            background-color: lightgrey;
        }

        .talk-bubble2 {
            margin: 40px;
            display: inline-block;
            position: relative;
            width: 500px;
            height: auto;
            background-color: #6d7fcc;
        }


        .tri-right.left-top:after {
            content: ' ';
            position: absolute;
            width: 0;
            height: 0;
            left: -20px;
            right: auto;
            top: 0px;
            bottom: auto;
            border: 22px solid;
            border-color: lightgrey transparent transparent transparent;
        }

        .tri-right.right-top:after {
            content: ' ';
            position: absolute;
            width: 0;
            height: 0;
            left: auto;
            right: -20px;
            top: 0px;
            bottom: auto;
            border: 20px solid;
            border-color: #6d7fcc transparent transparent transparent;
        }

        .talktext {
            padding: 1em;
            text-align: left;
            line-height: 1.5em;
        }

        .talktext p {
            /* remove webkit p margins */
            -webkit-margin-before: 0em;
            -webkit-margin-after: 0em;
            color: black;
        }

        .talktext2 p {
            /* remove webkit p margins */
            -webkit-margin-before: 0em;
            -webkit-margin-after: 0em;
            color: white;
        }

        .talktext2 {
            padding: 1em;
            text-align: left;
            line-height: 1.5em;
            color: white;
        }
        .info2 {
            margin-right: 3%;
        }
        .info{
            margin-left: 3%;
        }




    </style>
    <div class="container mt-0" id="fix">
        <h1 class="display-4 text-center">{{ sender.firstname }} {{ sender.lastname }}</h1>
        <hr style="background-color: #6d7fcc;"/>
    </div>
    <div id="messageScroll" style="overflow-y: scroll; overflow-x: hidden;  height: 55VH;">
        {% for m in messages %}
            {% if m.idSender == app.user %}
                <div class="info2 text-right">{{ m.date|date("d/m/Y") }}</div>
                <div class="row justify-content-end">
                    <div class="talk-bubble2 tri-right right-top  mb-0 mt-0">
                        <div class="talktext2">
                            <p>{{ m.content }} </p>
                        </div>
                    </div>
                </div>
                <div class="info2 text-right">  {{ m.date|date("H:i") }}</div>
            {% else %}
                <div class="info">{{ m.date|date("d/m/Y") }}  </div>
                <div class="row">
                    <div class="talk-bubble tri-right left-top mb-0 mt-0">
                        <div class="talktext">
                            <p> {{ m.content }}</p>
                        </div>
                    </div>
                </div>
                <div class="info">{{ m.date|date("H:i") }} </div>
            {% endif %}
        {% endfor %}
    </div>
    <hr style="background-color: #6d7fcc;"/>
    <div class="row">
        <div class="col pt-3 pb-3">
            {{ form_start(form) }}
            {{ form_widget(form.content, {"attr" : {"class" : "form-control", "placeholder" : "Votre message...", "required" : ""}}) }}
            <br>
            <input type="submit" value="Envoyer" style="background-color: #6d7fcc; color: white;"
                   class="btn btn-lg btn-block pt-2 pb-2">
            {{ form_end(form) }}
            <!--<textarea class="form-control" id="description" name="description" rows="3"></textarea><br />-->
        </div>
    </div>
{% endblock %}

DreamTeach/templates/forgotPassword.html.twig
{% extends "base.disconnect.html.twig" %}

{% block stylesheets %}<link rel="stylesheet" href="{{ asset('css/custom.css') }}">{% endblock %}

{% block title %}Mot de passe oublié{% endblock %}

{% block body %}
    <div class="container" id="card">
        <div class="card">
            <div class="card-header">
                <h1>Mot de passe oublié</h1>
            </div>
            <div class="card-body">
                <form method="post" action="{{ path('SendMailForgotPassword') }}" class="form-group row" >
                    <div class="container">
                        <p class="card-text">Renseignez votre adresse mail, nous vous enverrons un nouveau mot de passe.</p>
                        <label class="sr-only" for="inlineFormInputGroupUsername2">Adresse mail</label>
                        <div class="input-group mb-2 mr-sm-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fas fa-at"></i></div>
                            </div>
                            <input type="text" class="form-control" name="email" id="inlineFormInputGroupUsername2" placeholder="Adresse mail">
                        </div>
                        <br />
                        {% for flash in app.flashes('info') %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ flash }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                        {% for flash in app.flashes('success') %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ flash }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                        <br />
                        <button type="submit" class="btn btn-primary btn-block btn-lg">Réinitialiser</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

DreamTeach/templates/hangman.winner.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block body %}
    <div class="container  mt-5">
        <h1 class="text-center">Bravo !</h1>
        <hr style="background-color: #6d7fcc;"/>
        <div class="row mt-5">
            <div class="col-5">
                <img style="height: 100%; width: 100%;"
                     src="http://www.yalletonesolutionmart.com/assets/images/trophy.gif">
            </div>
            <div class="col-1"></div>
            <div class="col-6 align-self-center">
                <h4>Le mot était : {{ word }}</h4>
            </div>
        </div>
        <form action="{{ path('PlayHangman') }}" method="POST">
            <button class="btn btn-block mt-5" style="background-color: #6d7fcc;color: white;" type="submit">Rejouer</button>
        </form>
    </div>


{% endblock %}

DreamTeach/templates/messages.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}

{% block body %}
    <style>
        .messageDiv {
            border: 1px solid rgba(86, 61, 124, .2);
        }

    </style>
    <div class="container mt-2  text-center">
        <h1 class="display-4">Messagerie</h1>
    </div>

    <hr style="background-color: #6d7fcc;"/>
    <form action="{{ path('friend_list') }}" method="POST">
        <button class="btn btn-block" style="background-color: #6d7fcc;color: white;" type="submit"><i
                    class="fas fa-envelope p-3"></i>Nouveau message<i class="fas fa-plus p-3"></i></button>
    </form>
    {% if messages %}
        <p class="mt-3">Messages récents :</p>
        <div class="container mt-3">
            <div class="row text-center">
            </div>
            {% for m in messages %}
                <div class="row  messageDiv">
                    <div style="display: none">{{ m.idSender.uuid }}</div>
                    <div class="col2 col-lg-2 align-self-center">
                        {% if m.idSender.avatar %}
                            <img class="img-thumbnail img-fluid" height="100px" width="100px"
                                 src={{ asset('uploads/avatars/' ~ m.idSender.avatar) }}>
                        {% else %}
                            <img class="img-thumbnail img-fluid" height="100px" width="100px"
                                 src="{{ asset('img/imageBaseProfil.png') }}"
                            >
                        {% endif %}
                    </div>
                    <div class="col pt-3">
                        <h6>{{ m.idSender.firstName }} {{ m.idSender.lastName }}</h6>
                        <hr style="background-color: #6d7fcc;"/>
                        <p>{{ m.content|slice(0, 300) }}{% if m.content|length > 300 %} ...{% endif %}</p>
                        <p class="text-right">Le : {{ m.date|date("d/m/Y") }} à {{ m.date|date("H:i") }} </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="container pt-4">
            <div class="alert alert-danger" role="alert">
                Aucun message disponible !
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block javascripts %}
    <script>
        $(".messageDiv").mouseenter(function () {
            $(this).css("background-color", "#EFEFEF");
            $('body').css('cursor', 'pointer');
        });
        $(".messageDiv").mouseleave(function () {
            $(this).css("background-color", "white");
            $('body').css('cursor', 'default');
        });
        $(".messageDiv").click(function () {
            window.open("/showConversation/" + this.childNodes[1].innerHTML, "_self");
        })
    </script>
{% endblock %}

DreamTeach/templates/parametres.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil - {{ app.user.lastName }} {{ app.user.firstName }}{% endblock %}

{% block body %}
    <h1>Paramètres du compte</h1>
    <div class="container">
    </div>
    <div class="row align-self-center">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h6><i class="fas fa-user-edit fa-lg"></i>&nbsp;Vos informations personnelles</h6>
                </div>
                {{ form_start(formPassword) }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="nouveauMotDePasse">Nouveau mot de passe &nbsp;</label>
                        <a href="#"><i class="fas fa-pen" id="editPassword"></i></a>
                        {{ form_widget(formPassword.password, {'id' :  'nouveauMotDePasse', 'disabled': 'disabled', 'class': 'col'})}}
                        <small id="emailHelp" class="form-text text-muted">Le mot de passe doit contenir 8 caractères minimum</small>
                    </div>
                    <button type="submit" id="submitPassword" class="btn btn-primary" disabled>Modifier</button>
                    {{ form_end(formPassword) }}
                </div>
                {{ form_start(formEmailAddress) }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="nouvelEmail">Modifier l'email &nbsp;</label>
                        <a href="#"><i class="fas fa-pen" id="editEmail"></i></a>
                        {{ form_widget(formEmailAddress.emailAddress, {'id' :  'adresseEmail', 'disabled': 'disabled', 'class': 'col'})}}
                        <small id="emailHelp" class="form-text text-muted">L'email doit être du type xyz@example.com</small>
                    </div>
                    <button type="submit" id="submitEmail" class="btn btn-primary" disabled>Modifier</button>
                    {{ form_end(formEmailAddress) }}
                </div>
            </div>
        </div>
    {% block javascripts %}
        <script>
            $(document).ready(function () {
                $("#editEmail").click(function () {
                  $("#adresseEmail").attr("disabled", false);
                })
                $("#editPassword").click(function () {
                  $("#nouveauMotDePasse").attr("disabled", false);
                })
                $("#nouveauMotDePasse").keypress(function () {
                    if($("#nouveauMotDePasse").val().length >= 7) {
                        $("#submitPassword").removeAttr('disabled');
                    }
                })
                $("#nouveauMotDePasse").keydown(function(e) {
                    if($("#nouveauMotDePasse").val().length < 9) {
                        $("#submitPassword").attr("disabled", true);
                    }
                })

                $("#adresseEmail").keypress(function () {
                    if($("#adresseEmail").val().indexOf("@")  > 0 && ($("#adresseEmail").val().indexOf(".")  > 2 && $("#adresseEmail").val().indexOf(".")  < ($("#adresseEmail").val().length)-1)) {
                        $("#submitEmail").attr('disabled', false);
                    } else {
                        $("#submitEmail").attr('disabled', true);
                    }
                })
                $("#adresseEmail").keyup(function(e) {
                    if($("#adresseEmail").val().indexOf("@")  > 0 && ($("#adresseEmail").val().indexOf(".")  > 2 && $("#adresseEmail").val().indexOf(".")  < ($("#adresseEmail").val().length)-1)) {
                        $("#submitEmail").attr('disabled', false);
                    } else {
                        $("#submitEmail").attr('disabled', true);
                    }
                })
            });
        </script>
    </div>
    {% endblock %}

{% endblock %}

DreamTeach/templates/showQcms.html.twig
{% extends 'base.html.twig' %}

{% block title %}Qcms{% endblock %}

{% block body %}
    {% if qcms %}
    <div class="container">
        <div class="table-responsive m-b-40">
            <table class="table table-borderless table-data3">
                <thead class="thead-dark">
                <tr>
                    <th>Titre</th>
                    <th>Date limite</th>
                    <th>État</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for qcm in qcms %}
                    <tr>
                        <td>{{ qcm.title }}</td>
                        <td>{{ qcm.deadline|date('d M Y') }}</td>
                        {% if qcm.visible == 1 %}
                            <td id="createdMessage{{ qcm.id }}" class="process">Publié</td>
                        {% else %}
                            <td id="createdMessage{{ qcm.id }}" class="denied">Non publié</td>
                        {% endif %}
                        {% if qcm.authorId.id == user.id %}
                            <td class="text-center">
                                <a class="btn btn-warning" href="editQcm/{{ qcm.id }}" role="button"><i class="far fa-edit"></i> Éditer</a>
                            </td>
                        {% else %}
                            <td class="text-center">
                                <a class="btn btn-primary" href="{{ path('createQcm') }}">Répondre au QCM</a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
        <div class="container">
            <div class="alert alert-danger" role="alert">Aucun QCM disponible !</div>
        </div>
    {% endif %}
    <div class="container">
        <a href="{{ path('createQcm') }}" class="btn btn-success btn-lg btn-block"><i class="fas fa-plus-square"></i> Créer un nouveau QCM</a>
    </div>
{% endblock %}

{% block javascripts %}
{% endblock %}